version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"  

  pgadmin-compose:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "draandes@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "123456"
      ports:
        - "54321:80"
      depends_on:
        - db          