name: docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
    # Artifact name
        name: api-go-test
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: draandes
        password: ${{ secrets.PASSWORD_DOCKER_HUB }} 
    # Build's context is the set of files located in the specified PATH or URL
        context: .
    # Path to the Dockerfile
        file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
        push: true
    # List of tags
        tags: draandes/go_api_test:${{github.ref_name}}
