name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        go_version: ['1.21', '>=1.22.1']
        os_version: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Build-DB
      working-directory: ./
      run: infra/docker-compose build
      
    - name: Create-DB
      working-directory: ./
      run: infra/docker-compose up -d

    - name: Test
      working-directory: ./
      run: go test -v cmd/main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os_version }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./
      run: go build -v cmd/main.go
